all: array pgm timing

array: 
	$(MAKE) -C array

pgm: 
	$(MAKE) -C pgm

timing: 
	$(MAKE) -C timing

clean:
	$(MAKE) -C array clean
	$(MAKE) -C pgm clean
	$(MAKE) -C timing clean

.PHONY: array pgm timing clean
